#! /bin/sh
sh /home/c0ff33/.screenlayout/screenlayout.sh

pgrep -x sxhkd > /dev/null || sxhkd &
nitrogen --restore &
picom &
redshift -c ~/.config/redshift.conf &
/home/c0ff33/.config/bspwm/launch_polybar.sh

bspc monitor -d 1 2 3 4

bspc config border_width    2
bspc config window_gap      5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a "SFML works!" desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
